CREATE TABLE IF NOT EXISTS households (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS household_members (
 household_id uuid NOT NULL REFERENCES households(id), user_id text NOT NULL REFERENCES "user"(id),
 role text NOT NULL CHECK(role IN ('owner','member')), active boolean NOT NULL DEFAULT true,
 PRIMARY KEY(household_id,user_id), UNIQUE(user_id)
);
CREATE TABLE IF NOT EXISTS household_invites (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL REFERENCES households(id),
 email text NOT NULL, role text NOT NULL DEFAULT 'member' CHECK(role IN ('owner','member')), active boolean NOT NULL DEFAULT true,
 UNIQUE(household_id,email)
);
CREATE TABLE IF NOT EXISTS coffee_brands (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL REFERENCES households(id),
 name text NOT NULL, url text NOT NULL DEFAULT '', description text NOT NULL DEFAULT '', version int NOT NULL DEFAULT 1,
 created_by text REFERENCES "user"(id), UNIQUE(household_id,id), UNIQUE(household_id,name)
);
CREATE TABLE IF NOT EXISTS coffee_beans (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL REFERENCES households(id),
 brand_id uuid NOT NULL, name text NOT NULL, product_url text NOT NULL DEFAULT '', image_url text,
 roast text CHECK(roast IN ('약배전','중배전','강배전')), flavor text NOT NULL DEFAULT '',
 price int CHECK(price>=0), weight_g int CHECK(weight_g>0), version int NOT NULL DEFAULT 1, archived boolean NOT NULL DEFAULT false,
 created_by text REFERENCES "user"(id), created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(household_id,id), FOREIGN KEY(household_id,brand_id) REFERENCES coffee_brands(household_id,id)
);
CREATE UNIQUE INDEX IF NOT EXISTS bean_url_unique ON coffee_beans(household_id,product_url) WHERE product_url <> '';
CREATE TABLE IF NOT EXISTS coffee_preferences (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL, bean_id uuid NOT NULL, user_id text NOT NULL REFERENCES "user"(id),
 status text CHECK(status IN ('구매예정','먹어봄')), recommendation text CHECK(recommendation IN ('추천','보통','비추천')),
 note text NOT NULL DEFAULT '', version int NOT NULL DEFAULT 1,
 UNIQUE(household_id,bean_id,user_id), FOREIGN KEY(household_id,bean_id) REFERENCES coffee_beans(household_id,id)
);
CREATE TABLE IF NOT EXISTS coffee_machines (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL REFERENCES households(id), name text NOT NULL,
 UNIQUE(household_id,id), UNIQUE(household_id,name)
);
CREATE TABLE IF NOT EXISTS coffee_brew_settings (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL, bean_id uuid NOT NULL, machine_id uuid NOT NULL,
 user_id text NOT NULL REFERENCES "user"(id), grind double precision NOT NULL CHECK(grind>=0), dose double precision NOT NULL CHECK(dose>=0),
 note text NOT NULL DEFAULT '', created_at timestamptz NOT NULL DEFAULT now(),
 FOREIGN KEY(household_id,bean_id) REFERENCES coffee_beans(household_id,id), FOREIGN KEY(household_id,machine_id) REFERENCES coffee_machines(household_id,id)
);
CREATE TABLE IF NOT EXISTS wines (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL REFERENCES households(id), display_id bigint GENERATED BY DEFAULT AS IDENTITY,
 name text NOT NULL, english_name text NOT NULL DEFAULT '', producer text NOT NULL DEFAULT '',
 type text NOT NULL CHECK(type IN ('레드','화이트','로제','스파클링','디저트','주정강화')), country text NOT NULL DEFAULT '', region text NOT NULL DEFAULT '', grapes text NOT NULL DEFAULT '',
 vintage_kind text NOT NULL DEFAULT 'unknown' CHECK(vintage_kind IN ('year','non_vintage','unknown')), vintage int,
 volume_ml int CHECK(volume_ml>0), version int NOT NULL DEFAULT 1, archived boolean NOT NULL DEFAULT false, created_by text REFERENCES "user"(id),
 CHECK((vintage_kind='year' AND vintage BETWEEN 1800 AND 2200) OR (vintage_kind<>'year' AND vintage IS NULL)),
 UNIQUE(household_id,id), UNIQUE(household_id,display_id)
);
CREATE TABLE IF NOT EXISTS wine_purchases (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL, wine_id uuid NOT NULL,
 quantity int NOT NULL CHECK(quantity>0), unit_price int CHECK(unit_price>=0), purchased_on date NOT NULL, store text NOT NULL DEFAULT '',
 FOREIGN KEY(household_id,wine_id) REFERENCES wines(household_id,id), UNIQUE(household_id,id)
);
CREATE TABLE IF NOT EXISTS wine_stock_events (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL, wine_id uuid NOT NULL,
 kind text NOT NULL CHECK(kind IN ('receive','consume','adjust','reverse','opening_balance')), delta int NOT NULL CHECK(delta<>0),
 occurred_on date NOT NULL DEFAULT (now() AT TIME ZONE 'Asia/Seoul')::date, created_at timestamptz NOT NULL DEFAULT now(),
 created_by text NOT NULL REFERENCES "user"(id), reason text NOT NULL DEFAULT '', purchase_id uuid, reverses_id uuid,
 UNIQUE(household_id,id), UNIQUE(reverses_id), FOREIGN KEY(household_id,wine_id) REFERENCES wines(household_id,id),
 FOREIGN KEY(household_id,purchase_id) REFERENCES wine_purchases(household_id,id),
 FOREIGN KEY(household_id,reverses_id) REFERENCES wine_stock_events(household_id,id)
);
CREATE INDEX IF NOT EXISTS stock_by_wine ON wine_stock_events(household_id,wine_id,created_at);
CREATE TABLE IF NOT EXISTS wine_tastings (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL, wine_id uuid NOT NULL, user_id text NOT NULL REFERENCES "user"(id),
 tasted_on date NOT NULL, score int CHECK(score BETWEEN 0 AND 100), note text NOT NULL DEFAULT '', repurchase boolean, event_id uuid,
 FOREIGN KEY(household_id,wine_id) REFERENCES wines(household_id,id), FOREIGN KEY(household_id,event_id) REFERENCES wine_stock_events(household_id,id)
);
CREATE TABLE IF NOT EXISTS wine_glasses (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL REFERENCES households(id), name text NOT NULL,
 brand text NOT NULL DEFAULT '', type text NOT NULL, note text NOT NULL DEFAULT '', version int NOT NULL DEFAULT 1, created_by text REFERENCES "user"(id), UNIQUE(household_id,id)
);
CREATE TABLE IF NOT EXISTS mutation_requests (
 household_id uuid NOT NULL REFERENCES households(id), user_id text NOT NULL REFERENCES "user"(id), operation text NOT NULL,
 request_key uuid NOT NULL, input_hash text NOT NULL, result jsonb, created_at timestamptz NOT NULL DEFAULT now(),
 PRIMARY KEY(household_id,user_id,operation,request_key)
);
CREATE TABLE IF NOT EXISTS activity_log (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), household_id uuid NOT NULL REFERENCES households(id), user_id text NOT NULL REFERENCES "user"(id),
 operation text NOT NULL, channel text NOT NULL, client_id text, label text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS request_limits (
 key text PRIMARY KEY, count int NOT NULL, expires_at timestamptz NOT NULL
);
CREATE TABLE IF NOT EXISTS import_records (
 household_id uuid NOT NULL REFERENCES households(id), source text NOT NULL, source_id text NOT NULL, target_id uuid NOT NULL, raw jsonb NOT NULL,
 PRIMARY KEY(household_id,source,source_id)
);
