export const seedBrands = [
  {
    name: "커피 리브레",
    url: "https://smartstore.naver.com/coffeelibre",
  },
  {
    name: "토치커피",
    url: "https://smartstore.naver.com/toch",
  },
  {
    name: "노다웃커피(중저가)",
    url: "https://smartstore.naver.com/nodoubt_coffee",
  },
  {
    name: "전광수 커피",
    url: "https://brand.naver.com/jeonscoffeelab",
  },
  {
    name: "180 커피로스터스",
    url: "https://smartstore.naver.com/180coffeeroasters",
  },
  {
    name: "수달리 커피",
    url: "https://brand.naver.com/soodalicoffee",
  },
  {
    name: "모모스커피",
    url: "https://brand.naver.com/momoscoffee",
  },
  {
    name: "빈브라더스",
    url: "https://brand.naver.com/beanbrothers",
  },
  {
    name: "헤베커피",
    url: "https://brand.naver.com/hebecoffee",
  },
  {
    name: "아이덴티티 커피랩",
    url: "https://smartstore.naver.com/identity_coffeelab",
  },
];
export const seedBeans = [
  {
    name: "에스쇼콜라",
    brand: "모모스커피",
    url: "https://brand.naver.com/momoscoffee/products/10011962222",
    recommendation: "추천",
    grind: null,
    dose: null,
    note: "",
  },
  {
    name: "프루티봉봉",
    brand: "모모스커피",
    url: "https://brand.naver.com/momoscoffee/products/10032632384",
    recommendation: "추천",
    grind: 11,
    dose: 6,
    note: "",
  },
  {
    name: "블랙수트",
    brand: "빈브라더스",
    url: "https://brand.naver.com/beanbrothers/products/5296043969",
    recommendation: "보통",
    grind: 10,
    dose: 7,
    note: "",
  },
  {
    name: "세븐티 블렌드",
    brand: "빈브라더스",
    url: "https://brand.naver.com/beanbrothers/products/7971414842",
    recommendation: null,
    grind: null,
    dose: null,
    note: "",
  },
  {
    name: "벨벳화이트",
    brand: "빈브라더스",
    url: "https://brand.naver.com/beanbrothers/products/13458303252",
    recommendation: "추천",
    grind: 13,
    dose: 5,
    note: "",
  },
  {
    name: "배드블러드",
    brand: "커피 리브레",
    url: "https://smartstore.naver.com/coffeelibre/products/13140697107",
    recommendation: "추천",
    grind: 10,
    dose: 7,
    note: "",
  },
  {
    name: "칠린 블렌드",
    brand: "아이덴티티 커피랩",
    url: "https://smartstore.naver.com/identity_coffeelab/products/4705726740",
    recommendation: "추천",
    grind: 13,
    dose: 6,
    note: "",
  },
  {
    name: "미드센추리 블렌드",
    brand: "아이덴티티 커피랩",
    url: "https://smartstore.naver.com/identity_coffeelab/products/6684189550",
    recommendation: "비추천",
    grind: 12,
    dose: 5,
    note: "딸기향이 많이남",
  },
  {
    name: "밸런스 블렌드",
    brand: "헤베커피",
    url: "https://brand.naver.com/hebecoffee/products/4976337808",
    recommendation: null,
    grind: null,
    dose: null,
    note: "",
  },
  {
    name: "프레쉬 블렌드",
    brand: "헤베커피",
    url: "https://brand.naver.com/hebecoffee/products/7715276304",
    recommendation: "비추천",
    grind: null,
    dose: null,
    note: "",
  },
  {
    name: "노다웃 콜롬비아 카르타고 슈가케인 디카페인 다크로스트",
    brand: "노다웃커피(중저가)",
    url: "https://smartstore.naver.com/nodoubt_coffee/products/5365015136",
    recommendation: "비추천",
    grind: null,
    dose: null,
    note: "",
  },
];
